### PR TITLE
Created three verb functions to be used with magrittr %>% operators

### PR DESCRIPTION
**Pull request by chainsawriot**
I have tested the Authenticate, Collect, Create, LoadCredential, SaveCredential functions with Youtube, Facebook and Twitter but not Instagram. I cannot create an App that can access to the public endpoints. It should work..... should.... 

Magrittr has been added as Suggests, maybe should put it as Imports.

I basically touch nothing on the previous code except CollectDataFacebook.R and CollectDataInstagram.R. It will not affect the previous user experience that rely on side effect.

I will create the .Rd if this pull request is accepted.

### CODE REVIEW

**Comment by timothyjgraham** [comment]
Hi Chung-hong,

Just waiting for the go-ahead from Rob Ackland for merging the pull request. It is very impressive work! I will get in touch again asap. Thanks.

Tim

**Comment by timothyjgraham** [comment]
Hi again,

I have tested out Instagram collection and network creation. Data collection and bimodal network creation works fine (nice work BTW!), however there is no UI implementation yet for creating ego networks (`CreateEgoNetwork)`, so this needs to be addressed.

I am happy to merge the pull request after ego networks are implemented. At a glance I think it needs: 

1. An "ego" option for the `type` argument in the `Create` function
2. Modify the `CreateEgoNetwork` function to accept the `credential` argument

I want to implement Twitter ego networks in the future, so this will be beneficial for that too.

Thanks and once again really nice work. Your UI implementation greatly improves the package :)

Tim

**Comment by chainsawriot** [comment]
I have hesitation wrapping `CreateEgoNetwork` in the `Create` function because it works differently to other `Create*Network` functions. `CreateEgoNetwork` in large part is a data collection function.
(Sorry for being a fundamentalist functional programmer and the obsession with pure functions....)

I think a slightly better design is to create a `CollectInstagramEgo` (and a future `CollectTwitterEgo`) function that collect Ego network data with API Login Credential and username, and it returns a `dataSource` with class `ego`. (I think the Twitter and Instagram Ego network data should be similar, right? If they are drastically different, we have change the class to `twitterego` and `instagramego`)

Add a `ego` argument to `Collect` and default to False, if it is True than the `collector` function change to Collect*Ego functions according to the `datasource` in the input Credential.

And then, while pipe that `dataSource` from `Collect` to `Create` with the `type` argument of "ego", it return a ego network. Actually, regardless of `type`, 'dataSource` with `ego` always return a ego network.

i.e.

```{r}

Authenticate("instagram", appID = myAppID, appSecret = myAppSecret) %>% Collect(ego = TRUE, username = "cocacola") %>% Create("Ego")

# Create() default to "Actor", but still it will create an ego network because the dataSource is ego
Authenticate("instagram", appID = myAppID, appSecret = myAppSecret) %>% Collect(ego = TRUE, username = "cocacola") %>% Create 
```

Another design choice is not to include Collect*Ego functions, add "ego" option in `type`. When `type` is "ego", `Create` is now not anticipate `dataSource` but credential and username in the ... and use the same `CreateEgoNetwork` function to collect data and create ego network.

i.e.

```{r}
Authenticate("instagram", appID = myAppID, appSecret = myAppSecret) %>% Create("Ego", username = "cocacola")
```

Honestly, I don't like such design because it break the `Authenticate %>% Collect %>% Create` workflow. Also, in the documentation we will have a hard time explaining why `Create` is expecting credential rather than dataSource in such a case.

**Comment by chainsawriot** [comment]
A separate issue: 

I also want to change the `datasource` argument in the `Authenticate` function to `socialmedia` because we have a similarly named object called `dataSource`.

**Comment by timothyjgraham** [comment]
OK, this makes a lot of sense, and I understand the obsession for pure functions. I think the first suggestion for creating a new `CollectInstagramEgo` function sounds like the way forward. 

I am travelling for the next week so will not have a chance to work on it. I think Instagram ego networks needs to be resolved though before merging your pull request, because otherwise users have to authenticate again (the old way) before collecting data, and it could easily become confusing.

**Comment by timothyjgraham** [comment]
Also I agree about `datasource` and `dataSource` being too similar - good point.

**Comment by chainsawriot** [comment]
I will implement the Instagram Ego functionality (and also the .Rd) and then submit another pull request.

**Comment by timothyjgraham** [comment]
Great, thanks and I look forward to it.

**Pull request closed without merging**
